### ISSUE TITLE
Node 12 actions need to be moved to Node 16

### ISSUE THREAD

**Issue by suzialeksander** [obophenotype/ascomycete-phenotype-ontology#11]
Hey @balhoff, the last few runs have resulted in the following warning

> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.

Google says this might be just a quick update of the checkout version?

**Comment by matentzn** [comment]
I updated the release workflow, do you want to try running it again?

**Comment by suzialeksander** [comment]
I tried it twice just now but failed both, looks like it's genuinely unhappy now about something:  

> Run ./src/scripts/make_release.sh
> fatal: detected dubious ownership in repository at '/__w/ascomycete-phenotype-ontology/ascomycete-phenotype-ontology'
> To add an exception for this directory, call:
> 
> 	git config --global --add safe.directory /__w/ascomycete-phenotype-ontology/ascomycete-phenotype-ontology
> Error: Process completed with exit code 128.

**Comment by matentzn** [comment]
I will try a few things but will take me a moment or two - are you under great time pressure?

**Comment by suzialeksander** [comment]
Absolutely not under any pressure. Also, previous issue was only a warning not a failure, so this seems like it will run if reverted for... a few more months? GitHub says "summer 2023" but doesn't say if the old node will be killed off or just throw that error for a long while.

**Comment by matentzn** [comment]
I will revert it back if I cant figure it out when I try tomorrow :)

**Comment by matentzn** [comment]
Sorry @suzialeksander I restored the old action now, I couldn't figure out what was wrong. I made the action identical to other repos where it works. I don't think you have to worry about the warning, but when something fails, come back to me and I will sort it out for you!

**Comment by suzialeksander** [comment]
no worries, thanks for looking into it.  I expect this will work for at least a few more months so I'll close this for now.
