### ISSUE TITLE
APO version IRI does not work

### ISSUE THREAD

**Issue by zhengj2007** [obophenotype/ascomycete-phenotype-ontology#4]
The APO version IRI: http://purl.obolibrary.org/obo/apo/releases/2020-03-10/apo.owl
direct to a page 'Not found'.

I check the APO purl configuration file, apo.yml, (https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/apo.yml).

It does not set the version IRI in the file. It would be good to add in as other OBO Foundry ontologies.

**Comment by balhoff** [comment]
Version IRIs should work going forward, e.g.: http://purl.obolibrary.org/obo/apo/releases/2021-09-02/apo.owl
